export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Michael Scott",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpg",
    username: "Pam Beasley",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpg",
    username: "Jim Halpert",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpg",
    username: "Andy Bernard",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "Dwight Schrute",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpg",
    username: "Stanley Hudson",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpg",
    username: "Angela Martin",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpg",
    username: "Kevin Malone",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpg",
    username: "Rayan Miller",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpg",
    username: "Kelly Kapoor",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I wonder if there is a way to update the active state of a user for other users to know if their friend is online or offline in a Unity game.It needs to work where if a user's client/device crashes/shuts off, power outage or internet outage it will notify their friends.Thanks.",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc:"any help with below code?",
    photo: "assets/post/error/2.png",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    photo: "assets/post/error/1.png",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/error/3.png",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/error/2.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Todays challenge !!",
    photo: "assets/post/error/1.png",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    photo: "assets/post/error/3.png",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "I am currently trying to install PyTorch (using the installation commands posted on PyTorch.org for pip) and when I run the command, my computer completely freezes.I tried this multiple times with the same result. I had to restart the computer a few times as well. On my current try, I put -v when trying to install and the pip seems to be stuck on Looking up in the cache.I do not know how to proceed. As I mentioned, I've already tried this method multiple times. It worked the first time but did not install PyTorch as it gave me an error for not using --user.Are there any solutions to this?",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "I have a React frontend that uses jwt to authenticate with the Django backend. The backend works and is connecting just fine using django views, but when I try to proxy a request from React, it gives me a Connection Refused error.",
    photo: "assets/post/error/2.png",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo : "assets/post/error/1.png",
    desc: "Why the code inside a class gets executed even if we didn't call it or create an object, while the code inside a function doesn't get executed until we call it ?",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];